# Generated by Django 3.2.8 on 2021-10-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='urlToImage',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
